const exercises = [
  // ==================== NIVEL BÁSICO ====================
  {
    id: 1,
    level: 'basico',
    title: 'Seleccionar todos los productos',
    description: 'Muestra todos los productos de la tienda con todas sus columnas.',
    hint: 'Usa SELECT * para traer todas las columnas.',
    solution: 'SELECT * FROM products;',
    expectedColumns: ['id', 'name', 'price', 'stock', 'category_id'],
    topic: 'SELECT básico',
  },
  {
    id: 2,
    level: 'basico',
    title: 'Nombre y precio de los productos',
    description: 'Muestra solo el nombre y el precio de todos los productos.',
    hint: 'Selecciona columnas específicas separándolas con coma.',
    solution: 'SELECT name, price FROM products;',
    expectedColumns: ['name', 'price'],
    topic: 'SELECT columnas',
  },
  {
    id: 3,
    level: 'basico',
    title: 'Productos con precio mayor a 500€',
    description: 'Lista los productos que cuestan más de 500 euros.',
    hint: 'Usa WHERE con el operador > para filtrar.',
    solution: 'SELECT name, price FROM products WHERE price > 500;',
    expectedColumns: ['name', 'price'],
    topic: 'WHERE',
  },
  {
    id: 4,
    level: 'basico',
    title: 'Clientes de España',
    description: 'Muestra el nombre y la ciudad de todos los clientes que son de España.',
    hint: 'Filtra por el campo country usando WHERE y comparación de texto.',
    solution: "SELECT first_name, last_name, city FROM customers WHERE country = 'España';",
    expectedColumns: ['first_name', 'last_name', 'city'],
    topic: 'WHERE con texto',
  },
  {
    id: 5,
    level: 'basico',
    title: 'Productos ordenados por precio',
    description: 'Lista todos los productos ordenados de menor a mayor precio.',
    hint: 'Usa ORDER BY con ASC (ascendente).',
    solution: 'SELECT name, price FROM products ORDER BY price ASC;',
    expectedColumns: ['name', 'price'],
    topic: 'ORDER BY',
  },
  {
    id: 6,
    level: 'basico',
    title: 'Los 5 productos más caros',
    description: 'Muestra los 5 productos con mayor precio.',
    hint: 'Combina ORDER BY DESC con LIMIT.',
    solution: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 5;',
    expectedColumns: ['name', 'price'],
    topic: 'LIMIT',
  },
  {
    id: 7,
    level: 'basico',
    title: 'Contar todos los clientes',
    description: 'Cuenta cuántos clientes hay en total en la base de datos.',
    hint: 'Usa la función de agregación COUNT(*).',
    solution: 'SELECT COUNT(*) AS total_clientes FROM customers;',
    expectedColumns: ['total_clientes'],
    topic: 'COUNT',
  },
  {
    id: 8,
    level: 'basico',
    title: 'Precio promedio de productos',
    description: 'Calcula el precio promedio de todos los productos.',
    hint: 'Usa AVG() para calcular promedios.',
    solution: 'SELECT AVG(price) AS precio_promedio FROM products;',
    expectedColumns: ['precio_promedio'],
    topic: 'AVG',
  },

  // ==================== NIVEL INTERMEDIO ====================
  {
    id: 9,
    level: 'intermedio',
    title: 'Productos por categoría',
    description: 'Muestra el nombre del producto junto con el nombre de su categoría.',
    hint: 'Necesitas hacer un JOIN entre products y categories usando category_id.',
    solution: 'SELECT p.name AS producto, c.name AS categoria FROM products p JOIN categories c ON p.category_id = c.id;',
    expectedColumns: ['producto', 'categoria'],
    topic: 'JOIN',
  },
  {
    id: 10,
    level: 'intermedio',
    title: 'Cantidad de productos por categoría',
    description: 'Cuenta cuántos productos hay en cada categoría, mostrando el nombre de la categoría.',
    hint: 'Usa JOIN + GROUP BY + COUNT.',
    solution: 'SELECT c.name AS categoria, COUNT(p.id) AS cantidad FROM categories c LEFT JOIN products p ON c.id = p.category_id GROUP BY c.name ORDER BY cantidad DESC;',
    expectedColumns: ['categoria', 'cantidad'],
    topic: 'GROUP BY + COUNT',
  },
  {
    id: 11,
    level: 'intermedio',
    title: 'Pedidos con nombre del cliente',
    description: 'Lista todos los pedidos mostrando el nombre completo del cliente, el estado y el total.',
    hint: 'Haz JOIN entre orders y customers.',
    solution: "SELECT o.id, c.first_name || ' ' || c.last_name AS cliente, o.status, o.total FROM orders o JOIN customers c ON o.customer_id = c.id;",
    expectedColumns: ['id', 'cliente', 'status', 'total'],
    topic: 'JOIN con concatenación',
  },
  {
    id: 12,
    level: 'intermedio',
    title: 'Categorías con precio promedio',
    description: 'Muestra cada categoría con el precio promedio de sus productos, ordenado de mayor a menor.',
    hint: 'Usa JOIN + GROUP BY + AVG.',
    solution: 'SELECT c.name AS categoria, ROUND(AVG(p.price), 2) AS precio_promedio FROM categories c JOIN products p ON c.id = p.category_id GROUP BY c.name ORDER BY precio_promedio DESC;',
    expectedColumns: ['categoria', 'precio_promedio'],
    topic: 'GROUP BY + AVG',
  },
  {
    id: 13,
    level: 'intermedio',
    title: 'Clientes que han pedido más de una vez',
    description: 'Muestra los clientes que tienen más de un pedido registrado.',
    hint: 'Usa GROUP BY en customer_id y filtra con HAVING COUNT > 1.',
    solution: 'SELECT c.first_name, c.last_name, COUNT(o.id) AS num_pedidos FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.first_name, c.last_name HAVING COUNT(o.id) > 1;',
    expectedColumns: ['first_name', 'last_name', 'num_pedidos'],
    topic: 'HAVING',
  },
  {
    id: 14,
    level: 'intermedio',
    title: 'Productos sin stock suficiente',
    description: 'Lista los productos que tienen menos de 10 unidades en stock, con su categoría.',
    hint: 'Filtra con WHERE stock < 10 y añade un JOIN con categories.',
    solution: 'SELECT p.name, p.stock, c.name AS categoria FROM products p JOIN categories c ON p.category_id = c.id WHERE p.stock < 10 ORDER BY p.stock ASC;',
    expectedColumns: ['name', 'stock', 'categoria'],
    topic: 'JOIN + WHERE',
  },
  {
    id: 15,
    level: 'intermedio',
    title: 'Valoración promedio por producto',
    description: 'Muestra los productos que tienen reseñas con su valoración promedio.',
    hint: 'JOIN entre products y reviews, agrupa por producto y calcula AVG(rating).',
    solution: 'SELECT p.name, ROUND(AVG(r.rating), 1) AS valoracion_media, COUNT(r.id) AS num_resenas FROM products p JOIN reviews r ON p.id = r.product_id GROUP BY p.id, p.name ORDER BY valoracion_media DESC;',
    expectedColumns: ['name', 'valoracion_media', 'num_resenas'],
    topic: 'JOIN + AVG + GROUP BY',
  },
  {
    id: 16,
    level: 'intermedio',
    title: 'Empleados por departamento',
    description: 'Muestra cada departamento con el número de empleados y el salario promedio.',
    hint: 'JOIN entre employees y departments, agrupa por departamento.',
    solution: 'SELECT d.name AS departamento, COUNT(e.id) AS empleados, ROUND(AVG(e.salary), 2) AS salario_promedio FROM departments d LEFT JOIN employees e ON d.id = e.department_id GROUP BY d.id, d.name ORDER BY empleados DESC;',
    expectedColumns: ['departamento', 'empleados', 'salario_promedio'],
    topic: 'LEFT JOIN + GROUP BY',
  },

  // ==================== NIVEL AVANZADO ====================
  {
    id: 17,
    level: 'avanzado',
    title: 'Top 3 productos más vendidos',
    description: 'Muestra los 3 productos que más unidades se han vendido en total.',
    hint: 'JOIN entre order_items y products, agrupa por producto y suma la cantidad con SUM(quantity).',
    solution: 'SELECT p.name, SUM(oi.quantity) AS unidades_vendidas FROM products p JOIN order_items oi ON p.id = oi.product_id GROUP BY p.id, p.name ORDER BY unidades_vendidas DESC LIMIT 3;',
    expectedColumns: ['name', 'unidades_vendidas'],
    topic: 'SUM + GROUP BY + LIMIT',
  },
  {
    id: 18,
    level: 'avanzado',
    title: 'Clientes que nunca han pedido',
    description: 'Encuentra los clientes que no tienen ningún pedido.',
    hint: 'Usa LEFT JOIN entre customers y orders, filtra donde order_id sea NULL.',
    solution: 'SELECT c.first_name, c.last_name, c.email FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.id IS NULL;',
    expectedColumns: ['first_name', 'last_name', 'email'],
    topic: 'LEFT JOIN + IS NULL',
  },
  {
    id: 19,
    level: 'avanzado',
    title: 'Ingresos totales por mes',
    description: 'Calcula el total de ingresos agrupados por mes para los pedidos entregados.',
    hint: "Usa DATE_TRUNC o EXTRACT para agrupar por mes. Filtra con WHERE status = 'delivered'.",
    solution: "SELECT TO_CHAR(created_at, 'YYYY-MM') AS mes, SUM(total) AS ingresos FROM orders WHERE status = 'delivered' GROUP BY mes ORDER BY mes;",
    expectedColumns: ['mes', 'ingresos'],
    topic: 'Funciones de fecha + GROUP BY',
  },
  {
    id: 20,
    level: 'avanzado',
    title: 'Empleados con salario mayor al promedio',
    description: 'Lista los empleados cuyo salario supera el salario promedio de toda la empresa.',
    hint: 'Usa una subconsulta para calcular el promedio: WHERE salary > (SELECT AVG(salary) FROM employees).',
    solution: 'SELECT first_name, last_name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees) ORDER BY salary DESC;',
    expectedColumns: ['first_name', 'last_name', 'salary'],
    topic: 'Subconsulta',
  },
  {
    id: 21,
    level: 'avanzado',
    title: 'Ranking de clientes por gasto total',
    description: 'Muestra todos los clientes ordenados por su gasto total en pedidos entregados.',
    hint: "Filtra por status = 'delivered', agrupa por cliente y suma los totales.",
    solution: "SELECT c.first_name || ' ' || c.last_name AS cliente, c.city, SUM(o.total) AS gasto_total FROM customers c JOIN orders o ON c.id = o.customer_id WHERE o.status = 'delivered' GROUP BY c.id, c.first_name, c.last_name, c.city ORDER BY gasto_total DESC;",
    expectedColumns: ['cliente', 'city', 'gasto_total'],
    topic: 'JOIN + SUM + GROUP BY ordenado',
  },
  {
    id: 22,
    level: 'avanzado',
    title: 'Productos más y menos valorados',
    description: 'Muestra el producto con mayor valoración y el de menor valoración en la misma consulta usando UNION.',
    hint: 'Calcula el promedio de rating por producto y usa UNION para combinar el mejor y el peor.',
    solution: `(SELECT p.name, ROUND(AVG(r.rating), 2) AS valoracion, 'Mejor valorado' AS tipo
FROM products p JOIN reviews r ON p.id = r.product_id
GROUP BY p.id, p.name ORDER BY valoracion DESC LIMIT 1)
UNION
(SELECT p.name, ROUND(AVG(r.rating), 2) AS valoracion, 'Peor valorado' AS tipo
FROM products p JOIN reviews r ON p.id = r.product_id
GROUP BY p.id, p.name ORDER BY valoracion ASC LIMIT 1);`,
    expectedColumns: ['name', 'valoracion', 'tipo'],
    topic: 'UNION',
  },
  {
    id: 23,
    level: 'avanzado',
    title: 'Pedido más grande de cada cliente',
    description: 'Muestra el pedido de mayor importe para cada cliente (solo los que han pedido).',
    hint: 'Agrupa por cliente y usa MAX(total) para obtener el pedido máximo.',
    solution: "SELECT c.first_name || ' ' || c.last_name AS cliente, MAX(o.total) AS pedido_maximo FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.first_name, c.last_name ORDER BY pedido_maximo DESC;",
    expectedColumns: ['cliente', 'pedido_maximo'],
    topic: 'MAX + GROUP BY',
  },
  {
    id: 24,
    level: 'avanzado',
    title: 'Detalle completo de pedidos',
    description: 'Muestra un informe completo con: cliente, producto, cantidad, precio unitario y subtotal de cada línea de pedido.',
    hint: 'Necesitas hacer múltiples JOINs: orders → order_items → products y orders → customers.',
    solution: "SELECT c.first_name || ' ' || c.last_name AS cliente, p.name AS producto, oi.quantity AS cantidad, oi.unit_price AS precio_unitario, (oi.quantity * oi.unit_price) AS subtotal FROM orders o JOIN customers c ON o.customer_id = c.id JOIN order_items oi ON o.id = oi.order_id JOIN products p ON oi.product_id = p.id ORDER BY o.id, p.name;",
    expectedColumns: ['cliente', 'producto', 'cantidad', 'precio_unitario', 'subtotal'],
    topic: 'JOINs múltiples',
  },
];

module.exports = exercises;
