const exercises = [
  // ==================== NIVEL BÁSICO ====================
  {
    id: 1,
    level: 'basico',
    title: 'Seleccionar todos los productos',
    description: 'Muestra todos los productos de la tienda con todas sus columnas.',
    hint: 'Usa SELECT * para traer todas las columnas.',
    solution: 'SELECT * FROM products;',
    explanation: 'El asterisco (*) es un comodín que significa "todas las columnas". SQL lee la tabla entera de arriba a abajo y devuelve cada fila tal cual. Útil para explorar, pero en producción conviene listar columnas explícitamente para evitar traer datos innecesarios.',
    expectedColumns: ['id', 'name', 'price', 'stock', 'category_id'],
    topic: 'SELECT básico',
  },
  {
    id: 2,
    level: 'basico',
    title: 'Nombre y precio de los productos',
    description: 'Muestra solo el nombre y el precio de todos los productos.',
    hint: 'Selecciona columnas específicas separándolas con coma.',
    solution: 'SELECT name, price FROM products;',
    explanation: 'Al listar columnas concretas tras SELECT, solo esos campos viajan del servidor al cliente. La base de datos sigue leyendo toda la tabla internamente, pero descarta las columnas no pedidas antes de devolver el resultado.',
    expectedColumns: ['name', 'price'],
    topic: 'SELECT columnas',
  },
  {
    id: 3,
    level: 'basico',
    title: 'Productos con precio mayor a 500€',
    description: 'Lista los productos que cuestan más de 500 euros.',
    hint: 'Usa WHERE con el operador > para filtrar.',
    solution: 'SELECT name, price FROM products WHERE price > 500;',
    explanation: 'WHERE es el filtro de SQL: evalúa cada fila y solo deja pasar las que cumplen la condición. El operador `>` compara números. Otros operadores: `<`, `>=`, `<=`, `=`, `<>` (distinto). El filtro se aplica antes de devolver los datos.',
    expectedColumns: ['name', 'price'],
    topic: 'WHERE',
  },
  {
    id: 4,
    level: 'basico',
    title: 'Clientes de España',
    description: 'Muestra el nombre y la ciudad de todos los clientes que son de España.',
    hint: 'Filtra por el campo country usando WHERE y comparación de texto.',
    solution: "SELECT first_name, last_name, city FROM customers WHERE country = 'España';",
    explanation: "Las cadenas de texto en SQL se encierran en comillas simples ('...'). La comparación es exacta y sensible a mayúsculas en PostgreSQL: 'España' y 'españa' son distintos. Para buscar sin importar mayúsculas, usa LOWER(country) = 'españa'.",
    expectedColumns: ['first_name', 'last_name', 'city'],
    topic: 'WHERE con texto',
  },
  {
    id: 5,
    level: 'basico',
    title: 'Productos ordenados por precio',
    description: 'Lista todos los productos ordenados de menor a mayor precio.',
    hint: 'Usa ORDER BY con ASC (ascendente).',
    solution: 'SELECT name, price FROM products ORDER BY price ASC;',
    explanation: 'ORDER BY reordena las filas del resultado antes de devolverlas. ASC (ascendente, de menor a mayor) es el valor por defecto si no escribes nada. DESC va de mayor a menor. Sin ORDER BY, el orden de las filas no está garantizado.',
    expectedColumns: ['name', 'price'],
    topic: 'ORDER BY',
  },
  {
    id: 6,
    level: 'basico',
    title: 'Los 5 productos más caros',
    description: 'Muestra los 5 productos con mayor precio.',
    hint: 'Combina ORDER BY DESC con LIMIT.',
    solution: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 5;',
    explanation: 'LIMIT n corta el resultado tras las primeras n filas. Combinado con ORDER BY price DESC (mayor a menor) obtienes el "top N" de cualquier métrica. SQL primero ordena toda la tabla y luego aplica el límite.',
    expectedColumns: ['name', 'price'],
    topic: 'LIMIT',
  },
  {
    id: 7,
    level: 'basico',
    title: 'Contar todos los clientes',
    description: 'Cuenta cuántos clientes hay en total en la base de datos.',
    hint: 'Usa la función de agregación COUNT(*).',
    solution: 'SELECT COUNT(*) AS total_clientes FROM customers;',
    explanation: 'COUNT(*) es una función de agregación: resume todas las filas de la tabla en un único valor. AS le da un nombre descriptivo a la columna resultado (alias). COUNT(*) incluye filas con NULLs; COUNT(columna) las excluye.',
    expectedColumns: ['total_clientes'],
    topic: 'COUNT',
  },
  {
    id: 8,
    level: 'basico',
    title: 'Precio promedio de productos',
    description: 'Calcula el precio promedio de todos los productos.',
    hint: 'Usa AVG() para calcular promedios.',
    solution: 'SELECT AVG(price) AS precio_promedio FROM products;',
    explanation: 'AVG calcula la media aritmética (suma de valores / número de filas). Es otra función de agregación que colapsa todas las filas en un solo número. AVG ignora los NULLs automáticamente.',
    expectedColumns: ['precio_promedio'],
    topic: 'AVG',
  },

  // ==================== NIVEL INTERMEDIO ====================
  {
    id: 9,
    level: 'intermedio',
    title: 'Productos por categoría',
    description: 'Muestra el nombre del producto junto con el nombre de su categoría.',
    hint: 'Necesitas hacer un JOIN entre products y categories usando category_id.',
    solution: 'SELECT p.name AS producto, c.name AS categoria FROM products p JOIN categories c ON p.category_id = c.id;',
    explanation: 'JOIN (o INNER JOIN) combina filas de dos tablas donde se cumple la condición ON. Aquí, para cada producto busca la categoría cuyo id coincida con category_id del producto. Solo aparecen filas que tienen coincidencia en ambas tablas.',
    expectedColumns: ['producto', 'categoria'],
    topic: 'JOIN',
  },
  {
    id: 10,
    level: 'intermedio',
    title: 'Cantidad de productos por categoría',
    description: 'Cuenta cuántos productos hay en cada categoría, mostrando el nombre de la categoría.',
    hint: 'Usa JOIN + GROUP BY + COUNT.',
    solution: 'SELECT c.name AS categoria, COUNT(p.id) AS cantidad FROM categories c LEFT JOIN products p ON c.id = p.category_id GROUP BY c.name ORDER BY cantidad DESC;',
    explanation: 'LEFT JOIN incluye TODAS las categorías aunque no tengan productos. GROUP BY c.name agrupa todas las filas con el mismo nombre de categoría en una sola fila resumen. COUNT(p.id) cuenta productos en cada grupo (ignora NULLs si la categoría está vacía).',
    expectedColumns: ['categoria', 'cantidad'],
    topic: 'GROUP BY + COUNT',
  },
  {
    id: 11,
    level: 'intermedio',
    title: 'Pedidos con nombre del cliente',
    description: 'Lista todos los pedidos mostrando el nombre completo del cliente, el estado y el total.',
    hint: 'Haz JOIN entre orders y customers.',
    solution: "SELECT o.id, c.first_name || ' ' || c.last_name AS cliente, o.status, o.total FROM orders o JOIN customers c ON o.customer_id = c.id;",
    explanation: "El operador || concatena cadenas de texto en PostgreSQL. first_name || ' ' || last_name une nombre, espacio y apellido en un único campo. En otros motores como MySQL se usa CONCAT(). Los alias de tabla (o, c) hacen el código más corto y claro.",
    expectedColumns: ['id', 'cliente', 'status', 'total'],
    topic: 'JOIN con concatenación',
  },
  {
    id: 12,
    level: 'intermedio',
    title: 'Categorías con precio promedio',
    description: 'Muestra cada categoría con el precio promedio de sus productos, ordenado de mayor a menor.',
    hint: 'Usa JOIN + GROUP BY + AVG.',
    solution: 'SELECT c.name AS categoria, ROUND(AVG(p.price), 2) AS precio_promedio FROM categories c JOIN products p ON c.id = p.category_id GROUP BY c.name ORDER BY precio_promedio DESC;',
    explanation: 'ROUND(valor, decimales) redondea el número al número de decimales indicado. Las funciones de agregación como AVG suelen devolver muchos decimales; ROUND las hace legibles. GROUP BY c.name calcula el promedio por categoría por separado.',
    expectedColumns: ['categoria', 'precio_promedio'],
    topic: 'GROUP BY + AVG',
  },
  {
    id: 13,
    level: 'intermedio',
    title: 'Clientes que han pedido más de una vez',
    description: 'Muestra los clientes que tienen más de un pedido registrado.',
    hint: 'Usa GROUP BY en customer_id y filtra con HAVING COUNT > 1.',
    solution: 'SELECT c.first_name, c.last_name, COUNT(o.id) AS num_pedidos FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.first_name, c.last_name HAVING COUNT(o.id) > 1;',
    explanation: 'HAVING filtra grupos DESPUÉS de que GROUP BY los ha creado. La regla de oro: WHERE filtra filas individuales (antes del agrupamiento), HAVING filtra grupos (después). No puedes usar COUNT en WHERE porque COUNT aún no existe en esa fase.',
    expectedColumns: ['first_name', 'last_name', 'num_pedidos'],
    topic: 'HAVING',
  },
  {
    id: 14,
    level: 'intermedio',
    title: 'Productos sin stock suficiente',
    description: 'Lista los productos que tienen menos de 10 unidades en stock, con su categoría.',
    hint: 'Filtra con WHERE stock < 10 y añade un JOIN con categories.',
    solution: 'SELECT p.name, p.stock, c.name AS categoria FROM products p JOIN categories c ON p.category_id = c.id WHERE p.stock < 10 ORDER BY p.stock ASC;',
    explanation: 'WHERE y JOIN se pueden combinar libremente. SQL primero une las tablas y forma una tabla combinada, luego WHERE filtra las filas de ese resultado. El orden en SQL es: FROM → JOIN → WHERE → SELECT → ORDER BY.',
    expectedColumns: ['name', 'stock', 'categoria'],
    topic: 'JOIN + WHERE',
  },
  {
    id: 15,
    level: 'intermedio',
    title: 'Valoración promedio por producto',
    description: 'Muestra los productos que tienen reseñas con su valoración promedio.',
    hint: 'JOIN entre products y reviews, agrupa por producto y calcula AVG(rating).',
    solution: 'SELECT p.name, ROUND(AVG(r.rating), 1) AS valoracion_media, COUNT(r.id) AS num_resenas FROM products p JOIN reviews r ON p.id = r.product_id GROUP BY p.id, p.name ORDER BY valoracion_media DESC;',
    explanation: 'Al hacer JOIN entre products y reviews, solo aparecen los productos con al menos una reseña (INNER JOIN). GROUP BY p.id, p.name agrupa todas las reseñas de cada producto juntas. El id se incluye en el GROUP BY para evitar ambigüedad si dos productos tienen el mismo nombre.',
    expectedColumns: ['name', 'valoracion_media', 'num_resenas'],
    topic: 'JOIN + AVG + GROUP BY',
  },
  {
    id: 16,
    level: 'intermedio',
    title: 'Empleados por departamento',
    description: 'Muestra cada departamento con el número de empleados y el salario promedio.',
    hint: 'JOIN entre employees y departments, agrupa por departamento.',
    solution: 'SELECT d.name AS departamento, COUNT(e.id) AS empleados, ROUND(AVG(e.salary), 2) AS salario_promedio FROM departments d LEFT JOIN employees e ON d.id = e.department_id GROUP BY d.id, d.name ORDER BY empleados DESC;',
    explanation: 'LEFT JOIN garantiza que aparezcan TODOS los departamentos, incluidos los que no tienen ningún empleado (en cuyo caso COUNT devuelve 0 y AVG devuelve NULL). Con un JOIN normal, los departamentos vacíos desaparecerían del resultado.',
    expectedColumns: ['departamento', 'empleados', 'salario_promedio'],
    topic: 'LEFT JOIN + GROUP BY',
  },

  // ==================== NIVEL AVANZADO ====================
  {
    id: 17,
    level: 'avanzado',
    title: 'Top 3 productos más vendidos',
    description: 'Muestra los 3 productos que más unidades se han vendido en total.',
    hint: 'JOIN entre order_items y products, agrupa por producto y suma la cantidad con SUM(quantity).',
    solution: 'SELECT p.name, SUM(oi.quantity) AS unidades_vendidas FROM products p JOIN order_items oi ON p.id = oi.product_id GROUP BY p.id, p.name ORDER BY unidades_vendidas DESC LIMIT 3;',
    explanation: 'SUM(quantity) suma las unidades de todas las líneas de pedido de cada producto. Cada venta puede aparecer en múltiples filas (si el mismo producto se vendió en distintos pedidos), y SUM los acumula todos. LIMIT 3 tras ORDER BY DESC da el "podio".',
    expectedColumns: ['name', 'unidades_vendidas'],
    topic: 'SUM + GROUP BY + LIMIT',
  },
  {
    id: 18,
    level: 'avanzado',
    title: 'Clientes que nunca han pedido',
    description: 'Encuentra los clientes que no tienen ningún pedido.',
    hint: 'Usa LEFT JOIN entre customers y orders, filtra donde order_id sea NULL.',
    solution: 'SELECT c.first_name, c.last_name, c.email FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.id IS NULL;',
    explanation: 'Cuando un LEFT JOIN no encuentra fila en la tabla derecha (orders), rellena todas sus columnas con NULL. WHERE o.id IS NULL selecciona exactamente esos clientes sin pedidos. Este patrón (LEFT JOIN + IS NULL) es la forma clásica de encontrar registros "huérfanos".',
    expectedColumns: ['first_name', 'last_name', 'email'],
    topic: 'LEFT JOIN + IS NULL',
  },
  {
    id: 19,
    level: 'avanzado',
    title: 'Ingresos totales por mes',
    description: 'Calcula el total de ingresos agrupados por mes para los pedidos entregados.',
    hint: "Usa DATE_TRUNC o EXTRACT para agrupar por mes. Filtra con WHERE status = 'delivered'.",
    solution: "SELECT TO_CHAR(created_at, 'YYYY-MM') AS mes, SUM(total) AS ingresos FROM orders WHERE status = 'delivered' GROUP BY mes ORDER BY mes;",
    explanation: "TO_CHAR(fecha, 'YYYY-MM') convierte la fecha a texto con formato año-mes (ej. '2024-01'). Esto permite GROUP BY mes para agrupar todos los pedidos de enero juntos, todos los de febrero, etc. SUM(total) suma el importe de cada mes.",
    expectedColumns: ['mes', 'ingresos'],
    topic: 'Funciones de fecha + GROUP BY',
  },
  {
    id: 20,
    level: 'avanzado',
    title: 'Empleados con salario mayor al promedio',
    description: 'Lista los empleados cuyo salario supera el salario promedio de toda la empresa.',
    hint: 'Usa una subconsulta para calcular el promedio: WHERE salary > (SELECT AVG(salary) FROM employees).',
    solution: 'SELECT first_name, last_name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees) ORDER BY salary DESC;',
    explanation: 'Una subconsulta es un SELECT dentro de otro SELECT. El motor ejecuta primero la subconsulta interior (calcula el salario medio) y usa su resultado como un valor escalar en el WHERE exterior. Es equivalente a calcular el promedio por separado y hardcodearlo, pero mucho más robusto.',
    expectedColumns: ['first_name', 'last_name', 'salary'],
    topic: 'Subconsulta',
  },
  {
    id: 21,
    level: 'avanzado',
    title: 'Ranking de clientes por gasto total',
    description: 'Muestra todos los clientes ordenados por su gasto total en pedidos entregados.',
    hint: "Filtra por status = 'delivered', agrupa por cliente y suma los totales.",
    solution: "SELECT c.first_name || ' ' || c.last_name AS cliente, c.city, SUM(o.total) AS gasto_total FROM customers c JOIN orders o ON c.id = o.customer_id WHERE o.status = 'delivered' GROUP BY c.id, c.first_name, c.last_name, c.city ORDER BY gasto_total DESC;",
    explanation: "WHERE filtra antes del agrupamiento (solo pedidos 'delivered'). Luego GROUP BY agrupa por cliente y SUM acumula sus totales. ORDER BY puede referenciar el alias gasto_total que creamos con AS. PostgreSQL resuelve el alias en la fase de ordenación.",
    expectedColumns: ['cliente', 'city', 'gasto_total'],
    topic: 'JOIN + SUM + GROUP BY ordenado',
  },
  {
    id: 22,
    level: 'avanzado',
    title: 'Productos más y menos valorados',
    description: 'Muestra el producto con mayor valoración y el de menor valoración en la misma consulta usando UNION.',
    hint: 'Calcula el promedio de rating por producto y usa UNION para combinar el mejor y el peor.',
    solution: `(SELECT p.name, ROUND(AVG(r.rating), 2) AS valoracion, 'Mejor valorado' AS tipo
FROM products p JOIN reviews r ON p.id = r.product_id
GROUP BY p.id, p.name ORDER BY valoracion DESC LIMIT 1)
UNION
(SELECT p.name, ROUND(AVG(r.rating), 2) AS valoracion, 'Peor valorado' AS tipo
FROM products p JOIN reviews r ON p.id = r.product_id
GROUP BY p.id, p.name ORDER BY valoracion ASC LIMIT 1);`,
    explanation: 'UNION combina los resultados de dos SELECT en una sola tabla. Ambas consultas deben devolver el mismo número de columnas con tipos compatibles. UNION elimina filas duplicadas; UNION ALL las conserva (más rápido). Cada parte del UNION puede tener su propio ORDER BY con LIMIT.',
    expectedColumns: ['name', 'valoracion', 'tipo'],
    topic: 'UNION',
  },
  {
    id: 23,
    level: 'avanzado',
    title: 'Pedido más grande de cada cliente',
    description: 'Muestra el pedido de mayor importe para cada cliente (solo los que han pedido).',
    hint: 'Agrupa por cliente y usa MAX(total) para obtener el pedido máximo.',
    solution: "SELECT c.first_name || ' ' || c.last_name AS cliente, MAX(o.total) AS pedido_maximo FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.first_name, c.last_name ORDER BY pedido_maximo DESC;",
    explanation: 'MAX(o.total) devuelve el valor máximo dentro de cada grupo (un grupo = un cliente). Al agrupar por c.id el motor examina todos los pedidos de ese cliente y selecciona el importe más alto. Análogamente, MIN daría el pedido más pequeño.',
    expectedColumns: ['cliente', 'pedido_maximo'],
    topic: 'MAX + GROUP BY',
  },
  {
    id: 24,
    level: 'avanzado',
    title: 'Detalle completo de pedidos',
    description: 'Muestra un informe completo con: cliente, producto, cantidad, precio unitario y subtotal de cada línea de pedido.',
    hint: 'Necesitas hacer múltiples JOINs: orders → order_items → products y orders → customers.',
    solution: "SELECT c.first_name || ' ' || c.last_name AS cliente, p.name AS producto, oi.quantity AS cantidad, oi.unit_price AS precio_unitario, (oi.quantity * oi.unit_price) AS subtotal FROM orders o JOIN customers c ON o.customer_id = c.id JOIN order_items oi ON o.id = oi.order_id JOIN products p ON oi.product_id = p.id ORDER BY o.id, p.name;",
    explanation: 'Se pueden encadenar múltiples JOIN para cruzar tantas tablas como sea necesario. El motor construye la tabla resultante paso a paso: orders + customers, luego + order_items, luego + products. La expresión aritmética (quantity * unit_price) se evalúa en la cláusula SELECT para calcular el subtotal.',
    expectedColumns: ['cliente', 'producto', 'cantidad', 'precio_unitario', 'subtotal'],
    topic: 'JOINs múltiples',
  },

  // ==================== EXTRA ====================
  {
    id: 25,
    level: 'basico',
    title: 'Clientes ordenados por apellido',
    description: 'Muestra el nombre y apellido de todos los clientes, ordenados alfabéticamente por apellido.',
    hint: 'Usa ORDER BY sobre la columna last_name.',
    solution: 'SELECT first_name, last_name FROM customers ORDER BY last_name, first_name;',
    explanation: 'ORDER BY acepta múltiples columnas separadas por coma. Ordena primero por last_name; cuando hay empate (dos personas con el mismo apellido), aplica el segundo criterio (first_name). Esto garantiza un orden totalmente determinista.',
    expectedColumns: ['first_name', 'last_name'],
    topic: 'ORDER BY',
  },
  {
    id: 26,
    level: 'basico',
    title: 'Productos que empiezan por "S"',
    description: 'Lista los nombres de los productos cuyo nombre empieza por la letra S.',
    hint: "Usa WHERE con LIKE 'S%'.",
    solution: "SELECT name FROM products WHERE name LIKE 'S%' ORDER BY name;",
    explanation: "LIKE permite buscar patrones en texto. El % es el comodín 'cualquier secuencia de caracteres' (incluida la vacía). 'S%' = empieza por S. '%S' = termina en S. '%S%' = contiene S en cualquier posición. El subrayado _ representa exactamente un carácter.",
    expectedColumns: ['name'],
    topic: 'WHERE con texto',
  },
  {
    id: 27,
    level: 'intermedio',
    title: 'Número de reseñas por producto',
    description: 'Muestra los productos que tienen reseñas, con cuántas reseñas tiene cada uno.',
    hint: 'JOIN entre products y reviews, agrupa por producto y cuenta con COUNT.',
    solution: 'SELECT p.name, COUNT(r.id) AS num_resenas FROM products p JOIN reviews r ON p.id = r.product_id GROUP BY p.name ORDER BY num_resenas DESC, p.name;',
    explanation: 'Con un JOIN (INNER) solo aparecen los productos que tienen al menos una reseña, porque el JOIN descarta las filas sin coincidencia. Para incluir también los productos sin reseñas (con 0), habría que usar LEFT JOIN y COUNT ignoraría los NULLs.',
    expectedColumns: ['name', 'num_resenas'],
    topic: 'GROUP BY + COUNT',
  },
  {
    id: 28,
    level: 'intermedio',
    title: 'Clientes por país',
    description: 'Cuenta cuántos clientes hay en cada país, de mayor a menor.',
    hint: 'Agrupa por country y usa COUNT(*).',
    solution: 'SELECT country, COUNT(*) AS total FROM customers GROUP BY country ORDER BY total DESC, country;',
    explanation: 'GROUP BY country crea un grupo por cada valor distinto de país. COUNT(*) cuenta cuántas filas (clientes) hay en cada grupo. ORDER BY total DESC ordena de mayor a menor; el segundo criterio country ordena alfabéticamente los empates.',
    expectedColumns: ['country', 'total'],
    topic: 'GROUP BY',
  },
  {
    id: 29,
    level: 'avanzado',
    title: 'Producto más caro de cada categoría',
    description: 'Muestra cada categoría con el precio del producto más caro que contiene.',
    hint: 'JOIN categories con products, agrupa por categoría y usa MAX(price).',
    solution: 'SELECT c.name AS categoria, MAX(p.price) AS precio_max FROM categories c JOIN products p ON c.id = p.category_id GROUP BY c.name ORDER BY precio_max DESC;',
    explanation: 'Al hacer JOIN de categorías con productos y GROUP BY categoría, el motor agrupa todos los productos de cada categoría juntos. MAX(p.price) selecciona el precio más alto dentro de cada grupo. El resultado es una fila por categoría con su producto estrella.',
    expectedColumns: ['categoria', 'precio_max'],
    topic: 'MAX + GROUP BY',
  },
  {
    id: 30,
    level: 'avanzado',
    title: 'Ingresos totales por categoría',
    description: 'Calcula cuánto dinero ha generado cada categoría sumando todas las líneas de pedido (cantidad × precio).',
    hint: 'Encadena JOINs: categories → products → order_items, y usa SUM(quantity * unit_price).',
    solution: 'SELECT c.name AS categoria, SUM(oi.quantity * oi.unit_price) AS ingresos FROM categories c JOIN products p ON c.id = p.category_id JOIN order_items oi ON p.id = oi.product_id GROUP BY c.name ORDER BY ingresos DESC;',
    explanation: 'Tres tablas unidas con JOIN: categories → products → order_items. Para llegar de categorías a líneas de pedido hay que pasar por productos (el puente). SUM(quantity * unit_price) calcula el ingreso de cada línea y los suma todos por categoría. Las expresiones aritméticas dentro de funciones de agregación son válidas.',
    expectedColumns: ['categoria', 'ingresos'],
    topic: 'JOINs múltiples',
  },
];

module.exports = exercises;
