// Ejercicios del escenario "banco" (schema banco)
const exercises = [
  {
    id: 301, scenario: 'banco', level: 'basico',
    title: 'Todas las sucursales',
    description: 'Muestra el nombre y la ciudad de todas las sucursales, ordenadas por ciudad.',
    hint: 'SELECT de dos columnas + ORDER BY city.',
    solution: 'SELECT name, city FROM branches ORDER BY city, name;',
    explanation: 'ORDER BY city, name ordena primero por ciudad y, en caso de empate (varias sucursales en la misma ciudad), por nombre. Así el listado es estable y predecible.',
    topic: 'SELECT + ORDER BY',
  },
  {
    id: 302, scenario: 'banco', level: 'basico',
    title: 'Cuentas con saldo alto',
    description: 'Lista las cuentas con un saldo superior a 10000, de mayor a menor saldo.',
    hint: 'WHERE balance > 10000 y ORDER BY balance DESC.',
    solution: 'SELECT id, account_type, balance FROM accounts WHERE balance > 10000 ORDER BY balance DESC;',
    explanation: 'WHERE balance > 10000 filtra solo las cuentas con saldo mayor a esa cifra. ORDER BY balance DESC las ordena de mayor a menor para ver primero las cuentas más cuantiosas.',
    topic: 'WHERE + ORDER BY',
  },
  {
    id: 303, scenario: 'banco', level: 'basico',
    title: 'Clientes de Madrid',
    description: 'Muestra el nombre y apellido de los clientes que viven en Madrid.',
    hint: "Filtra con WHERE city = 'Madrid'.",
    solution: "SELECT first_name, last_name FROM customers WHERE city = 'Madrid' ORDER BY last_name;",
    explanation: "La comparación de texto con = es exacta y sensible a mayúsculas en PostgreSQL. ORDER BY last_name ordena los clientes alfabéticamente por apellido.",
    topic: 'WHERE con texto',
  },
  {
    id: 304, scenario: 'banco', level: 'intermedio',
    title: 'Cuentas con su titular',
    description: 'Muestra cada cuenta (tipo y saldo) junto al nombre completo de su cliente titular.',
    hint: 'JOIN entre accounts y customers usando customer_id.',
    solution: "SELECT a.id, c.first_name || ' ' || c.last_name AS titular, a.account_type, a.balance FROM accounts a JOIN customers c ON a.customer_id = c.id ORDER BY a.id;",
    explanation: 'JOIN une cada cuenta con su cliente comparando customer_id (en accounts) con id (en customers). El operador || concatena nombre y apellido en un solo campo "titular".',
    topic: 'JOIN con concatenación',
  },
  {
    id: 305, scenario: 'banco', level: 'intermedio',
    title: 'Cuentas por tipo',
    description: 'Cuenta cuántas cuentas hay de cada tipo (corriente y ahorro).',
    hint: 'Agrupa por account_type y usa COUNT(*).',
    solution: 'SELECT account_type, COUNT(*) AS total FROM accounts GROUP BY account_type ORDER BY total DESC, account_type;',
    explanation: 'GROUP BY account_type crea un grupo por cada tipo de cuenta. COUNT(*) cuenta cuántas cuentas hay en cada grupo. No hace falta JOIN porque toda la información está en la tabla accounts.',
    topic: 'GROUP BY + COUNT',
  },
  {
    id: 306, scenario: 'banco', level: 'intermedio',
    title: 'Saldo total por sucursal',
    description: 'Muestra cada sucursal con la suma de los saldos de las cuentas que gestiona, de mayor a menor.',
    hint: 'JOIN branches con accounts, agrupa por sucursal y usa SUM(balance).',
    solution: 'SELECT b.name AS sucursal, SUM(a.balance) AS saldo_total FROM branches b JOIN accounts a ON b.id = a.branch_id GROUP BY b.id, b.name ORDER BY saldo_total DESC;',
    explanation: 'SUM(a.balance) suma los saldos de todas las cuentas de cada sucursal. GROUP BY b.id, b.name agrupa por sucursal. Se incluye el id en el GROUP BY para evitar ambigüedad si dos sucursales tuvieran el mismo nombre.',
    topic: 'JOIN + SUM + GROUP BY',
  },
  {
    id: 307, scenario: 'banco', level: 'avanzado',
    title: 'Top 3 clientes por patrimonio',
    description: 'Muestra los 3 clientes con mayor saldo total sumando todas sus cuentas.',
    hint: 'JOIN customers con accounts, suma los saldos por cliente y ordena descendente con LIMIT 3.',
    solution: "SELECT c.first_name || ' ' || c.last_name AS cliente, SUM(a.balance) AS patrimonio FROM customers c JOIN accounts a ON c.id = a.customer_id GROUP BY c.id, c.first_name, c.last_name ORDER BY patrimonio DESC LIMIT 3;",
    explanation: 'Un cliente puede tener varias cuentas, así que SUM(a.balance) acumula el saldo de todas ellas tras agrupar por cliente. ORDER BY patrimonio DESC + LIMIT 3 selecciona a los tres clientes más ricos del banco.',
    topic: 'JOIN + SUM + GROUP BY + LIMIT',
  },
  {
    id: 308, scenario: 'banco', level: 'avanzado',
    title: 'Préstamos en mora',
    description: 'Lista los préstamos en estado "moroso" con el nombre del cliente, el importe y el tipo de interés.',
    hint: "JOIN loans con customers filtrando WHERE status = 'moroso'.",
    solution: "SELECT c.first_name || ' ' || c.last_name AS cliente, l.amount AS importe, l.interest_rate AS interes FROM loans l JOIN customers c ON l.customer_id = c.id WHERE l.status = 'moroso' ORDER BY l.amount DESC;",
    explanation: "WHERE l.status = 'moroso' filtra solo los préstamos impagados. El JOIN trae el nombre del cliente asociado a cada préstamo. Es el tipo de informe que un banco usaría para gestionar su riesgo de impago.",
    topic: 'JOIN + WHERE',
  },
  {
    id: 309, scenario: 'banco', level: 'avanzado',
    title: 'Clientes sin préstamos',
    description: 'Encuentra los clientes que no tienen ningún préstamo concedido.',
    hint: 'LEFT JOIN de customers con loans y filtra donde el préstamo es NULL.',
    solution: 'SELECT c.first_name, c.last_name, c.city FROM customers c LEFT JOIN loans l ON c.id = l.customer_id WHERE l.id IS NULL ORDER BY c.last_name;',
    explanation: 'LEFT JOIN incluye a TODOS los clientes aunque no tengan préstamos; en esos casos la tabla loans aporta NULLs. WHERE l.id IS NULL aísla exactamente a los clientes sin ningún préstamo. Patrón clásico LEFT JOIN + IS NULL para hallar registros sin relación.',
    topic: 'LEFT JOIN + IS NULL',
  },
];

module.exports = exercises;
